/**
 * Build Orbit Paint region art into static JSON, SVG thumbs, and the manifest.
 * Run: node scripts/paint/build.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { mandalas } from './mandalas.mjs';
import { scenes } from './scenes.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const paintDir = path.join(root, 'public', 'paint');
const thumbDir = path.join(paintDir, 'thumbs');

function finalize(art) {
  const used = new Map();
  for (const region of art.regions) {
    used.set(region.n, (used.get(region.n) || 0) + 1);
  }
  const map = new Map();
  const colors = [];
  for (let n = 1; n <= art.colors.length; n++) {
    if (!used.has(n)) continue;
    map.set(n, colors.length + 1);
    colors.push(art.colors[n - 1]);
  }
  art.colors = colors;
  for (const region of art.regions) region.n = map.get(region.n);
  const count = art.regions.length;
  if (count < 80 || count > 400) {
    throw new Error(`${art.id} has ${count} regions (want 80–400)`);
  }
  if (colors.length < 6) throw new Error(`${art.id} only has ${colors.length} colors`);
  const ids = new Set(art.regions.map((region) => region.d));
  if (ids.size !== art.regions.length) {
    /* identical paths can repeat (two same circles); allow */
  }
  for (const region of art.regions) {
    if (!region.d.startsWith('M') || !region.d.endsWith('Z')) {
      throw new Error(`${art.id} bad path`);
    }
  }
  return art;
}

function thumbSvg(art) {
  const [ , , w, h] = art.viewBox.split(' ').map(Number);
  const parts = [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">`,
    `<rect width="${w}" height="${h}" fill="#f6f1e8"/>`,
  ];
  for (const region of art.regions) {
    const fill = art.colors[region.n - 1].hex;
    parts.push(
      `<path d="${region.d}" fill="${fill}" stroke="#5c4a55" stroke-width="2.4" stroke-linejoin="round" stroke-linecap="round"/>`
    );
  }
  parts.push('</svg>');
  return parts.join('');
}

function manifestSource(list) {
  const rows = list.map((art) => {
    const entry = {
      id: art.id,
      title: art.title,
      category: art.category,
      difficulty: art.difficulty,
      regionCount: art.regions.length,
      colorCount: art.colors.length,
      viewBox: art.viewBox,
    };
    return `  Object.freeze(${JSON.stringify(entry)})`;
  });
  return `/** Generated by scripts/paint/build.mjs. Do not edit by hand. */\nexport const PICTURES = Object.freeze([\n${rows.join(',\n')},\n]);\n\nexport const CATEGORIES = Object.freeze([\n  Object.freeze({ id: 'mandala', title: 'Mandalas' }),\n  Object.freeze({ id: 'manga', title: 'Manga' }),\n  Object.freeze({ id: 'maerchen', title: 'Märchen' }),\n]);\n`;
}

const arts = [...mandalas(), ...scenes()].map((art) => {
  art.viewBox = `0 0 ${art.w} ${art.h}`;
  return finalize(art);
});

fs.mkdirSync(thumbDir, { recursive: true });
for (const art of arts) {
  const json = {
    id: art.id,
    viewBox: art.viewBox,
    colors: art.colors,
    regions: art.regions,
  };
  fs.writeFileSync(path.join(paintDir, `${art.id}.json`), JSON.stringify(json));
  fs.writeFileSync(path.join(thumbDir, `${art.id}.svg`), thumbSvg(art));
  console.log(
    `${art.id.padEnd(12)} ${String(art.regions.length).padStart(3)} regions  ${String(art.colors.length).padStart(2)} colors  ${art.category}  ${art.difficulty}`
  );
}
fs.writeFileSync(path.join(root, 'src', 'paint-manifest.js'), manifestSource(arts));
console.log(`wrote ${arts.length} pictures`);
